enum ActionTypes {

    SET_PANEL_TAB = 'SET_PANEL_TAB',
    SET_BODY_FILTER = 'SET_BODY_FILTER',
    GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
    TOGGLE_BODY_EVENT_FORM = 'TOGGLE_BODY_EVENT_FORM',
    TOGGLE_BODY_FORM = 'TOGGLE_BODY_FORM'

}

export default ActionTypes