enum ActionTypes {

    SET_PANEL_TAB = 'SET_PANEL_TAB',
    SET_BODY_FILTER = 'SET_BODY_FILTER',
    ADD_NOTIFICATION = 'ADD_NOTIFICATION',
    GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'

}

export default ActionTypes