enum ActionTypes {

    GET_UNAUTH_USER_SENT = 'GET_UNAUTH_USER_SENT',
    GET_UNAUTH_USER_SUCCESS = 'GET_UNAUTH_USER_SUCCESS',
    GET_UNAUTH_USER_FAIL = 'GET_UNAUTH_USER_FAIL'

}

export default ActionTypes