enum ActionTypes {

    SIGN_UP = 'SIGN_UP',
    GET_UNAUTH_USER = 'GET_UNAUTH_USER',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',

    GET_MESSAGES = 'GET_MESSAGES',
    ADD_MESSAGE = 'ADD_MESSAGE',
    DELETE_MESSAGE = 'DELETE_MESSAGE',
    RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
    RECEIVE_ONLINE_USERS = 'RECEIVE_ONLINE_USERS',
    RECEIVE_CONNECTION = 'RECEIVE_CONNECTION',
    RECEIVE_DISCONNECTION = 'RECEIVE_DISCONNECTION',

    TOGGLE_STICKY_CHAT = 'TOGGLE_STICKY_CHAT'

}

export default ActionTypes