export default {

    GET_APPROVALS: 'GET_APPROVALS',
    APPROVE: 'APPROVE',
    DISAPPROVE: 'DISAPPROVE',
    RECEIVE_REMOVE_APPROVAL: 'RECEIVE_REMOVE_APPROVAL',
    RECEIVE_APPROVAL: 'RECEIVE_APPROVAL'

}