enum ActionTypes {

    GET_BODIES = 'GET_BODIES',
    GET_BODY_BY_ID = 'GET_BODY_BY_ID',
    CHANGE_VIEW_SIZE = 'CHANGE_VIEW_SIZE',
    SELECT_BODY = 'SELECT_BODY',
    TOGGLE_LABELS = 'TOGGLE_LABELS',
    TOGGLE_LIGHT = 'TOGGLE_LIGHT',
    TOGGLE_ORBITS = 'TOGGLE_ORBITS'
}

export default ActionTypes