enum ActionTypes {

    GET_BODIES = 'GET_BODIES',
    GET_BODY_BY_ID = 'GET_BODY_BY_ID',
    CHANGE_VIEW_SIZE = 'CHANGE_VIEW_SIZE',
    SELECT_BODY = 'SELECT_BODY',
    TOGGLE_LABELS = 'TOGGLE_LABELS',
    TOGGLE_LIGHT = 'TOGGLE_LIGHT',
    TOGGLE_ORBITS = 'TOGGLE_ORBITS',
    TOGGLE_ANSWERS = 'TOGGLE_ANSWERS',
    LOCAL_VOTE = 'LOCAL_VOTE',
    VOTE = 'VOTE',
    ADD_ANSWER = 'ADD_ANSWER',
    ADD_DISCUSSION = 'ADD_DISCUSSION',
    LOCAL_ADD_ANSWER = 'LOCAL_ADD_ANSWER',
    LOCAL_ADD_DISCUSSION = 'LOCAL_ADD_DISCUSSION',
    TOGGLE_NEW_DISCUSSION = 'TOGGLE_NEW_DISCUSSION'
}

export default ActionTypes