/**
 * action types for SystemModule.
 */
enum ActionTypes {

    SET_CONTEXT_MENU = 'SET_CONTEXT_MENU',
    SET_ALERT = 'SET_ALERT',
    TOGGLE_UI = 'TOGGLE_UI',
    TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN',
    TOGGLE_ALERT = 'TOGGLE_ALERT',
    TOGGLE_CONTEXT_MENU = 'TOGGLE_CONTEXT_MENU',
    RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION',
    REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

}

export default ActionTypes