/**
 * action types for SystemModule.
 */
enum ActionTypes {

    SET_CONTEXT_MENU = 'SET_CONTEXT_MENU',
    TOGGLE_UI = 'TOGGLE_UI',
    TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN',
    TOGGLE_CONTEXT_MENU = 'TOGGLE_CONTEXT_MENU',
    RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION',
    REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
    FADE_OUT_NOTIFICATION = 'FADE_OUT_NOTIFICATION',
    RECEIVE_CHANGE_SCORE = 'RECEIVE_CHANGE_SCORE'

}

export default ActionTypes